version: 2
updates:
  - package-ecosystem: npm
    # Files stored in repository root
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@jingofi/default-token-list'
      - dependency-name: '@uniswap/token-lists'
      - dependency-name: '@jingofi/widgets'
    reviewers:
      - 'Uniswap/dependabot-reviewers'
